// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"database/sql"
)

type Dashboard struct {
	ProductID    string
	UnitsSold    sql.NullInt32
	Color        string
	CostPrice    int64
	SellingPrice int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	DeletedAt    sql.NullInt64
}
